name: Domenico Tagliente
favicon: null
layout_spectrum: 0.09288
typography_spectrum: 0.64868
title: THE WAVE AND THE DEVICE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b49679'
    - '#736049'
    - '#412d25'
    - '#f2c899'
    - '#b34731'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
