name: Domenico Tagliente
favicon: null
layout_spectrum: 0.34061
typography_spectrum: 0.94727
title: THE WAVE AND THE DEVICE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#06050b'
    - '#5b6463'
    - '#79a0d7'
    - '#e1cc95'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
