name: Domenico Tagliente
favicon: null
layout_spectrum: 0.33889
typography_spectrum: 0.64868
title: THE WAVE AND THE DEVICE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f0d7'
    - '#3c474d'
    - '#2f8594'
    - '#6f96a7'
    - '#18192d'
  brandStrength: 0.0625
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
