name: Domenico Tagliente
favicon: null
layout_spectrum: 0.95932
typography_spectrum: 0.64868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8fff7'
    - '#050402'
    - '#29406f'
    - '#7dc0fc'
    - '#7b695c'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
