name: Domenico Tagliente
favicon: null
layout_spectrum: 0.33889
typography_spectrum: 0.64868
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7b7b5'
    - '#48484a'
    - '#726e6f'
    - '#1a1917'
    - '#ee5a38'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
